#!/bin/sh /etc/rc.common

START=99
STOP=10

start() {
    # -------------------------------------------------------------------------
    # mDNS (5353) - AirPlay, Chromecast, HomeKit, Matter, ESPHome, Printers
    # -------------------------------------------------------------------------
    /usr/sbin/udpbroadcastrelay --id 1 --port 5353 --dev br-lan --dev br-smarthome --multicast 224.0.0.251 --blockid 4 -f

    /usr/sbin/udpbroadcastrelay --id 4 --port 5353 --dev br-open --dev br-smarthome --multicast 224.0.0.251 --allowcidr 192.168.20.0/24 --allowcidr 192.168.0.150/32 --allowcidr 192.168.0.231/32 --blockid 1 -f

    # -------------------------------------------------------------------------
    # SSDP / UPnP (1900) - DIAL Smart TVs, DLNA, Hue, Sonos
    # Hue/Sonos ride on this relay too (lan<->SmartHome side is unrestricted) -
    # no separate instance needed for them.
    # -------------------------------------------------------------------------
    /usr/sbin/udpbroadcastrelay --id 2 --port 1900 --multicast 239.255.255.250 --dev br-lan --dev br-smarthome -s 1.1.1.2 --msearch dial --blockid 3 -f

    /usr/sbin/udpbroadcastrelay --id 3 --port 1900 --multicast 239.255.255.250 --dev br-open --dev br-smarthome -s 1.1.1.3 --msearch dial --allowcidr 192.168.20.0/24 --allowcidr 192.168.0.243/32 --allowcidr 192.168.0.198/32 --blockid 2 -f

    # -------------------------------------------------------------------------
    # TP-Link Kasa/Tapo (9999) - lan<->SmartHome only, no Open access
    # -------------------------------------------------------------------------
    /usr/sbin/udpbroadcastrelay --id 5 --port 9999 --dev br-lan --dev br-smarthome -s 1.1.1.5 -f

    # -------------------------------------------------------------------------
    # Tuya / Smart Life (6666, 6667) - lan<->SmartHome only, no Open access
    # -------------------------------------------------------------------------
    /usr/sbin/udpbroadcastrelay --id 6 --port 6666 --dev br-lan --dev br-smarthome -s 1.1.1.6 -f
    /usr/sbin/udpbroadcastrelay --id 7 --port 6667 --dev br-lan --dev br-smarthome -s 1.1.1.7 -f

    # -------------------------------------------------------------------------
    # LIFX (56700) - lan<->SmartHome only, no Open access
    # -------------------------------------------------------------------------
    /usr/sbin/udpbroadcastrelay --id 8 --port 56700 --dev br-lan --dev br-smarthome -s 1.1.1.8 -f

    # -------------------------------------------------------------------------
    # Xiaomi / Yeelight (54321) - lan<->SmartHome only, no Open access
    # -------------------------------------------------------------------------
    /usr/sbin/udpbroadcastrelay --id 9 --port 54321 --dev br-lan --dev br-smarthome -s 1.1.1.9 -f
}

stop() {
    killall udpbroadcastrelay
}
