#!/bin/sh
chmod +x /etc/ssh/*.sh 2>/dev/null
chmod +x /usr/sbin/udpbroadcastrelay 2>/dev/null
chmod +x /etc/init.d/udpbroadcastrelay 2>/dev/null
chmod +x /etc/init.d/disable_guests_wifi‎ 2>/dev/null
chmod +x /etc/init.d/wakeuppc‎ 2>/dev/null
exit 0
