name: Quick Binary Compile

on:
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Install Compiler & Build
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu git
          git clone https://github.com/udp-redux/udp-broadcast-relay-redux.git
          cd udp-broadcast-relay-redux
          aarch64-linux-gnu-gcc -O3 -static main.c -o udp-broadcast-relay-redux

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: udp-broadcast-relay-redux-static
          path: udp-broadcast-relay-redux/udp-broadcast-relay-redux
